```{r eval=FALSE, message=FALSE, warning=FALSE,include=FALSE}
#Instalación de Paquetes
install.packages("readxl")
install.packages("readr")
```

```{r message=FALSE, warning=FALSE, include=FALSE}
# Usando read.csv()
Ventas_csv1 <- read.csv("salesforcourse-4fe2kehu.csv")

# Usando readr::read_csv() (más rápido y con mejor manejo de tipos de datos)
library(readr)
Ventas_csv2 <- read_csv("salesforcourse-4fe2kehu.csv")

# Cargar un archivo de texto con delimitador de tabulaciones
Ventas_txt <- read.table("salesforcourse-4fe2kehu.txt", header = TRUE, sep = "\t")

# Cargar el paquete readxl
library(readxl)
Ventas_xlsx <- read_excel("salesforcourse-4fe2kehu.xlsx")
```

```{r include=FALSE}
# Ver las primeras filas
print(Ventas_xlsx)

# Ver las dimensiones del dataset (filas y columnas)
dim(Ventas_xlsx)
```

```{r eval=FALSE, include=FALSE}
# Ver la estructura del dataset
str(Ventas_xlsx)
```

```{r eval=FALSE, include=FALSE}
# Ver las primeras 6 filas
head(Ventas_xlsx)

# Ver las últimas 6 filas
tail(Ventas_xlsx)
```

```{r eval=FALSE, include=FALSE}
# Ver los nombres de las columnas
names(Ventas_xlsx)
```

```{r eval=FALSE, include=FALSE}
# Obtener un resumen estadístico del dataset
summary(Ventas_xlsx)
```

```{r eval=FALSE, include=FALSE}
# Especificar que la columna "index" sea leída como carácter
Ventas_csv1 <- read_csv("salesforcourse-4fe2kehu.csv", col_types = cols(index = col_character()))
Ventas_csv2 <- read.csv("salesforcourse-4fe2kehu.csv", colClasses = c(index = "character"))
Ventas_xlsx <- read_excel("salesforcourse-4fe2kehu.xlsx", col_types = c("text"))
```

```{r}
# Convertir la columna "ID" a carácter
Ventas_xlsx$index <- as.character(Ventas_xlsx$index)
# Verificar el tipo de dato de la columna "ID"
class(Ventas_xlsx$index)
```


